name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install OpenGL GLUT
      use: ./.github/linux-cpp-build.sh
    - name: qmake
      run: qmake
    - name: make
      run: make
