name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW & GCC
      uses: egor-tensin/setup-mingw@v2
      uses: egor-tensin/setup-gcc@v1
      with:
        platform: x64
    - name: make
      run: make
    - name: make check
      run: make check
