name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: (dir 2>&1 *`|echo CMD);&<# rem #>echo PowerShell
    - uses: actions/checkout@v2
    - name: Set up MinGW & GCC
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: make
      shell: cmd
      run: echo $SHELL && make
    - name: make check
      shell: cmd
      run: make check
