name: Build Windows

on:
  push:
    branches: [ master , version-windows ]
  pull_request:
    branches: [ master , version-windows ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW & GCC
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: test
      run: cl.exe -v
    - name: qmake
      run: qmake
    - name: make
      run: make
